/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ListPropertyRouteImport } from './routes/list-property'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminPortalRouteImport } from './routes/admin-portal'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as DashboardViewingsRouteImport } from './routes/dashboard.viewings'
import { Route as DashboardSubscriptionRouteImport } from './routes/dashboard.subscription'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardPropertiesRouteImport } from './routes/dashboard.properties'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardFavoritesRouteImport } from './routes/dashboard.favorites'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPropertiesRouteImport } from './routes/admin.properties'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as DashboardPropertiesNewRouteImport } from './routes/dashboard.properties.new'
import { Route as DashboardPropertiesIdEditRouteImport } from './routes/dashboard.properties.$id.edit'
import { Route as ApiPublicHooksSubscriptionsTickRouteImport } from './routes/api/public/hooks/subscriptions-tick'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ListPropertyRoute = ListPropertyRouteImport.update({
  id: '/list-property',
  path: '/list-property',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPortalRoute = AdminPortalRouteImport.update({
  id: '/admin-portal',
  path: '/admin-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardViewingsRoute = DashboardViewingsRouteImport.update({
  id: '/viewings',
  path: '/viewings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubscriptionRoute = DashboardSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPropertiesRoute = DashboardPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFavoritesRoute = DashboardFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropertiesRoute = AdminPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardPropertiesNewRoute = DashboardPropertiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardPropertiesRoute,
} as any)
const DashboardPropertiesIdEditRoute =
  DashboardPropertiesIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => DashboardPropertiesRoute,
  } as any)
const ApiPublicHooksSubscriptionsTickRoute =
  ApiPublicHooksSubscriptionsTickRouteImport.update({
    id: '/api/public/hooks/subscriptions-tick',
    path: '/api/public/hooks/subscriptions-tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-portal': typeof AdminPortalRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/list-property': typeof ListPropertyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/properties': typeof DashboardPropertiesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/dashboard/viewings': typeof DashboardViewingsRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/properties/new': typeof DashboardPropertiesNewRoute
  '/api/public/hooks/subscriptions-tick': typeof ApiPublicHooksSubscriptionsTickRoute
  '/dashboard/properties/$id/edit': typeof DashboardPropertiesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-portal': typeof AdminPortalRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/list-property': typeof ListPropertyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/properties': typeof DashboardPropertiesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/dashboard/viewings': typeof DashboardViewingsRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/properties/new': typeof DashboardPropertiesNewRoute
  '/api/public/hooks/subscriptions-tick': typeof ApiPublicHooksSubscriptionsTickRoute
  '/dashboard/properties/$id/edit': typeof DashboardPropertiesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-portal': typeof AdminPortalRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/list-property': typeof ListPropertyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/properties': typeof DashboardPropertiesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/dashboard/viewings': typeof DashboardViewingsRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/properties/new': typeof DashboardPropertiesNewRoute
  '/api/public/hooks/subscriptions-tick': typeof ApiPublicHooksSubscriptionsTickRoute
  '/dashboard/properties/$id/edit': typeof DashboardPropertiesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-portal'
    | '/auth'
    | '/browse'
    | '/contact'
    | '/dashboard'
    | '/list-property'
    | '/sitemap.xml'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/properties'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/dashboard/favorites'
    | '/dashboard/messages'
    | '/dashboard/properties'
    | '/dashboard/settings'
    | '/dashboard/subscription'
    | '/dashboard/viewings'
    | '/properties/$id'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/properties/new'
    | '/api/public/hooks/subscriptions-tick'
    | '/dashboard/properties/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-portal'
    | '/auth'
    | '/browse'
    | '/contact'
    | '/list-property'
    | '/sitemap.xml'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/properties'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/dashboard/favorites'
    | '/dashboard/messages'
    | '/dashboard/properties'
    | '/dashboard/settings'
    | '/dashboard/subscription'
    | '/dashboard/viewings'
    | '/properties/$id'
    | '/admin'
    | '/dashboard'
    | '/dashboard/properties/new'
    | '/api/public/hooks/subscriptions-tick'
    | '/dashboard/properties/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-portal'
    | '/auth'
    | '/browse'
    | '/contact'
    | '/dashboard'
    | '/list-property'
    | '/sitemap.xml'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/properties'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/dashboard/favorites'
    | '/dashboard/messages'
    | '/dashboard/properties'
    | '/dashboard/settings'
    | '/dashboard/subscription'
    | '/dashboard/viewings'
    | '/properties/$id'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/properties/new'
    | '/api/public/hooks/subscriptions-tick'
    | '/dashboard/properties/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminPortalRoute: typeof AdminPortalRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ListPropertyRoute: typeof ListPropertyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  ApiPublicHooksSubscriptionsTickRoute: typeof ApiPublicHooksSubscriptionsTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-property': {
      id: '/list-property'
      path: '/list-property'
      fullPath: '/list-property'
      preLoaderRoute: typeof ListPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-portal': {
      id: '/admin-portal'
      path: '/admin-portal'
      fullPath: '/admin-portal'
      preLoaderRoute: typeof AdminPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/viewings': {
      id: '/dashboard/viewings'
      path: '/viewings'
      fullPath: '/dashboard/viewings'
      preLoaderRoute: typeof DashboardViewingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subscription': {
      id: '/dashboard/subscription'
      path: '/subscription'
      fullPath: '/dashboard/subscription'
      preLoaderRoute: typeof DashboardSubscriptionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/properties': {
      id: '/dashboard/properties'
      path: '/properties'
      fullPath: '/dashboard/properties'
      preLoaderRoute: typeof DashboardPropertiesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/favorites': {
      id: '/dashboard/favorites'
      path: '/favorites'
      fullPath: '/dashboard/favorites'
      preLoaderRoute: typeof DashboardFavoritesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/properties': {
      id: '/admin/properties'
      path: '/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AdminPropertiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/properties/new': {
      id: '/dashboard/properties/new'
      path: '/new'
      fullPath: '/dashboard/properties/new'
      preLoaderRoute: typeof DashboardPropertiesNewRouteImport
      parentRoute: typeof DashboardPropertiesRoute
    }
    '/dashboard/properties/$id/edit': {
      id: '/dashboard/properties/$id/edit'
      path: '/$id/edit'
      fullPath: '/dashboard/properties/$id/edit'
      preLoaderRoute: typeof DashboardPropertiesIdEditRouteImport
      parentRoute: typeof DashboardPropertiesRoute
    }
    '/api/public/hooks/subscriptions-tick': {
      id: '/api/public/hooks/subscriptions-tick'
      path: '/api/public/hooks/subscriptions-tick'
      fullPath: '/api/public/hooks/subscriptions-tick'
      preLoaderRoute: typeof ApiPublicHooksSubscriptionsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminPropertiesRoute: typeof AdminPropertiesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminPropertiesRoute: AdminPropertiesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardPropertiesRouteChildren {
  DashboardPropertiesNewRoute: typeof DashboardPropertiesNewRoute
  DashboardPropertiesIdEditRoute: typeof DashboardPropertiesIdEditRoute
}

const DashboardPropertiesRouteChildren: DashboardPropertiesRouteChildren = {
  DashboardPropertiesNewRoute: DashboardPropertiesNewRoute,
  DashboardPropertiesIdEditRoute: DashboardPropertiesIdEditRoute,
}

const DashboardPropertiesRouteWithChildren =
  DashboardPropertiesRoute._addFileChildren(DashboardPropertiesRouteChildren)

interface DashboardRouteChildren {
  DashboardFavoritesRoute: typeof DashboardFavoritesRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardPropertiesRoute: typeof DashboardPropertiesRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSubscriptionRoute: typeof DashboardSubscriptionRoute
  DashboardViewingsRoute: typeof DashboardViewingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardFavoritesRoute: DashboardFavoritesRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardPropertiesRoute: DashboardPropertiesRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSubscriptionRoute: DashboardSubscriptionRoute,
  DashboardViewingsRoute: DashboardViewingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminPortalRoute: AdminPortalRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ListPropertyRoute: ListPropertyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  ApiPublicHooksSubscriptionsTickRoute: ApiPublicHooksSubscriptionsTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
